# Generated by Django 2.1.2 on 2018-10-27 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=30)),
                ('run', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.IntegerField()),
                ('region', models.EmailField(max_length=30)),
                ('comuna', models.EmailField(max_length=30)),
                ('tipo_vivienda', models.EmailField(max_length=30)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
