# Generated by Django 2.1.2 on 2018-10-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181027_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='comuna',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='region',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='tipo_vivienda',
            field=models.CharField(max_length=30),
        ),
    ]
