# Generated by Django 2.1.2 on 2018-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181027_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='fotografia',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
