# Generated by Django 2.1.2 on 2018-10-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181027_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescatado',
            old_name='fotografia',
            new_name='foto',
        ),
    ]
